version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: ".env"
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_USERNAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
